### ISSUE TITLE
Doesn't work with CoffeeScript 2

### ISSUE THREAD

**Issue by crcdng** [jamis/csmazes#4]
As a workaround, you can install CoffeeScript 1 

`npm install --save-dev coffeescript@1.12.7`

or globally (sudo on Mac)

`sudo npm install -g coffeescript@1.12.7`

**Comment by jamis** [comment]
What happens with CoffeeScript 2? (I mean, yeah, I could install it, but I don't have time to troubleshoot it at the moment, and I'd rather just have the world handed to me on a platter anyway... :))

**Comment by crcdng** [comment]
For the time being, I created a PR for the Readme
EDIT: needs more investigation

**Comment by crcdng** [comment]
> What happens with CoffeeScript 2? (I mean, yeah, I could install it, but I don't have time to troubleshoot it at the moment, and I'd rather just have the world handed to me on a platter anyway... :))

would you rather...

- [ ] keep it on CoffeeScript 1 and add a comment to the Readme? It's a bit more complicated than I thought initially, as people might have CoffeeScript 2 globally so its safer to install  CoffeeScript 1 locally, but then `cake build` needs to be called from the node_modules folder
- [ ] update the code to CoffeeScript 2? 
- [ ] move to JavaScript / ES 6?

**Comment by meeeeeGeeka** [comment]
Could you upload the javascript files? this would make things way easier 
building with cake also failedfor me :(

**Comment by mjrlowe** [comment]
I'm having trouble running this even with Coffeescript 1.12.7. Is there any chance you could upload the Javascript files?

**Comment by jamis-vian** [comment]
Ultimately, I no longer have time or inclination to maintain this project. Sorry. :( If I were to do it all over again, I would just do it in vanilla JS (and maybe someday I will, but not soon, alas). If anyone is itching to update this project to latest CoffeeScript, you have my blessing. And if anyone wants to port it to vanilla JS, you have my blessing as well.

**Comment by jamis** [comment]
Ultimately, I no longer have time or inclination to maintain this project. Sorry. :( If I were to do it all over again, I would just do it in vanilla JS (and maybe someday I will, but not soon, alas). If anyone is itching to update this project to latest CoffeeScript, you have my blessing. And if anyone wants to port it to vanilla JS, you have my blessing as well.

**Comment by crcdng** [comment]
> Ultimately, I no longer have time or inclination to maintain this project. Sorry. 

Are you talking just this repo or mazes in general :) ?

**Comment by jamis-vian** [comment]
:) the repo. Though even my maze-time is pretty limited these days!

**Comment by jamis** [comment]
:) the repo. Though even my maze-time is pretty limited these days!

**Comment by crcdng** [comment]
Okay. I might port the book Ruby code to Dart if I have time. 

For the issue here, I would close it now and leave the note here: WONTFIX. If someone needs the CoffeeScript code, they would have to fork and dig into it.
