### ISSUE TITLE
Add topics to this Github repository 

### ISSUE THREAD

**Issue by mjrlowe** [jamis/csmazes#6]
This will make for easier searching and it will mean it can be more easily grouped with other similar projects.

I recommend adding the "maze" topic, but other topics such as "CofeeScript" and "generator" may be suitable too.

**Comment by jamis** [comment]
Sure! I've never used that feature of GitHub, though, and a cursory look through the Settings page doesn't show anything that seems relevant. Can you show me how to add topics?

**Comment by mjrlowe** [comment]
See [this](https://docs.github.com/en/enterprise/2.15/user/articles/classifying-your-repository-with-topics) article. There should be an "add topics" button on the main page of the repo, underneath the title.

**Comment by jamis** [comment]
Thanks! My page looks nothing like that in the article, but after a bit more poking around I discovered that I could set topics via the gear icon on the far right of the page. I've added "maze" and "generator". Thanks for the suggestion!

**Comment by mjrlowe** [comment]
Looks good! Sorry, I think the article I linked was a little outdated but I'm glad you got it working.

I would change the `mazes` topic to `maze`, though, as it's the variant that's more widely used.
